# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autorisation(object):
    def setupUi(self, autorisation):
        autorisation.setObjectName("autorisation")
        autorisation.resize(440, 141)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(autorisation.sizePolicy().hasHeightForWidth())
        autorisation.setSizePolicy(sizePolicy)
        autorisation.setMinimumSize(QtCore.QSize(440, 141))
        autorisation.setMaximumSize(QtCore.QSize(440, 141))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../3-PO/autorisation-main/pythonProject1/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        autorisation.setWindowIcon(icon)
        autorisation.setStyleSheet("font: 14pt \"Calibri\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(autorisation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.username_value = QtWidgets.QLineEdit(autorisation)
        self.username_value.setObjectName("username_value")
        self.verticalLayout.addWidget(self.username_value)
        self.password_value = QtWidgets.QLineEdit(autorisation)
        self.password_value.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_value.setObjectName("password_value")
        self.verticalLayout.addWidget(self.password_value)
        self.login_btn = QtWidgets.QPushButton(autorisation)
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout.addWidget(self.login_btn)
        self.reg_btn = QtWidgets.QPushButton(autorisation)
        self.reg_btn.setObjectName("reg_btn")
        self.verticalLayout.addWidget(self.reg_btn)

        self.retranslateUi(autorisation)
        QtCore.QMetaObject.connectSlotsByName(autorisation)

    def retranslateUi(self, autorisation):
        _translate = QtCore.QCoreApplication.translate
        autorisation.setWindowTitle(_translate("autorisation", "Авторизация"))
        self.username_value.setPlaceholderText(_translate("autorisation", "Введите логин..."))
        self.password_value.setPlaceholderText(_translate("autorisation", "Введите пароль..."))
        self.login_btn.setText(_translate("autorisation", "Войти в систему"))
        self.reg_btn.setText(_translate("autorisation", "Зарегестрироваться"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    autorisation = QtWidgets.QWidget()
    ui = Ui_autorisation()
    ui.setupUi(autorisation)
    autorisation.show()
    sys.exit(app.exec_())
